# Generated by Django 3.0.5 on 2020-04-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choices',
            name='isCorrect',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='choices',
            name='points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
