# Generated by Django 3.0.5 on 2020-04-19 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
        ('quiz', '0002_auto_20200417_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquiz',
            name='module',
        ),
        migrations.RemoveField(
            model_name='userquiz',
            name='user',
        ),
        migrations.AlterField(
            model_name='questions',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='modules.Module'),
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='UserQuiz',
        ),
    ]
