# Generated by Django 3.0.5 on 2020-04-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200419_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='isCorrect',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='choices',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
