# Generated by Django 3.0.5 on 2020-04-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20200420_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='answerName',
            field=models.CharField(max_length=255, verbose_name='Відповідь'),
        ),
        migrations.AlterField(
            model_name='choices',
            name='isCorrect',
            field=models.BooleanField(default=False, verbose_name='Правильний?'),
        ),
        migrations.AlterField(
            model_name='choices',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Кількість баллів'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='questionName',
            field=models.CharField(max_length=255, verbose_name='Питання'),
        ),
    ]
