# Generated by Django 3.0.5 on 2020-04-25 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва факультету')),
            ],
            options={
                'verbose_name': 'Факультет',
                'verbose_name_plural': 'Факультети',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Сathedra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва кафедри')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cathedrals', to='department.Faculty')),
            ],
            options={
                'verbose_name': 'Кафедра',
                'verbose_name_plural': 'Кафедри',
                'ordering': ('name',),
            },
        ),
    ]
