# Generated by Django 3.0.5 on 2020-04-25 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_auto_20200423_2158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ('name',), 'verbose_name': 'Модуль', 'verbose_name_plural': 'Модули'},
        ),
        migrations.AlterModelOptions(
            name='userquiz',
            options={'verbose_name': 'Пройденый тест пользователем', 'verbose_name_plural': 'Пройденые тесты пользователями'},
        ),
    ]
