# Generated by Django 3.0.5 on 2020-04-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthdate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата народження'),
        ),
    ]
