# Generated by Django 3.0.5 on 2020-04-25 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200425_1811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='isTeacher',
            new_name='isLecturer',
        ),
    ]
