# Generated by Django 3.0.5 on 2020-04-27 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_group'),
        ('accounts', '0004_auto_20200425_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cathedra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturers', to='department.Сathedra'),
        ),
        migrations.AddField(
            model_name='profile',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='department.Group'),
        ),
    ]
