# Generated by Django 3.0.5 on 2020-04-27 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_group'),
        ('accounts', '0005_auto_20200427_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturers', to='department.Faculty'),
        ),
    ]
