# Generated by Django 3.0.5 on 2020-04-27 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_auto_20200427_2005'),
        ('accounts', '0010_auto_20200427_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cathedra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturers', to='department.Сathedra', verbose_name='Кафедра'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturers', to='department.Faculty', verbose_name='Факультет'),
        ),
    ]
